### PR TITLE
WIP bugfix

### LINKED ISSUE #20: hxcpp issue
### Describe your bug here.

it gives me this error in the terminal & i am building it regular for macos 
Screen Shot 2024-03-12 at 7 57 13 PM

### Command Prompt/Terminal logs (if existing)

_No response_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### PR DESCRIPTION
**Pull request by moxie-coder**
closes #20 
@JonnycatMeow I don’t have a Mac to test this on so if you could lend a hand here

### CODE REVIEW

**Comment by JonnycatMeow** [comment]
ok i will test it

**Comment by JonnycatMeow** [comment]
Screen Shot 2024-03-15 at 9 09 30 PM

**Comment by riconuts** [comment]
@JonnycatMeow 
we changed the antialiasing get and set functions so you could try again if you'd like to

**Comment by JonnycatMeow** [comment]
oh ok

**Comment by JonnycatMeow** [comment]
Screen Shot 2024-04-21 at 2 45 27 PM

**Comment by JonnycatMeow** [comment]
this bugfix works

**Pull request merged**
